### ISSUE TITLE
Background and font

### ISSUE THREAD

**Issue by ghost** [FoxesAreCute/cyberfoxBBDTheme#1]
The main part (the cyber threat background map) does not work
font is too small and doesnt change with scaling
![image](https://user-images.githubusercontent.com/85327029/127114857-f8cf43b4-e4c9-49e8-b1fb-2cadd3298a04.png)

**Comment by FoxesAreCute** [comment]
Background servers are offline until I can host long term. For the font I will fix that ASAP.

**Comment by ghost** [comment]
Alright understood. Have a great day!
